# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd api-lambda
      - yarn install
  pre_build:
    commands:
      - echo "Cleaning .tsbuildinfo..."
      - rm -rf .tsbuildinfo
  build:
    commands:
      - echo "Running NestJS build..."
      - yarn build
      - echo "Navigating back to root..."
      - cd ..
      - echo "Running SAM build..."
      - sam build
      - echo "Copying dist directory..."
      - cp -r ./api-lambda/dist ./.aws-sam/build/ApiLambdaFunction/
  post_build:
    commands:
      - echo "Running SAM deploy..."
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - .aws-sam/**/*
  discard-paths: no